spring:
  application:
  name: epam-high-task2


  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate.ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        dialect: ${SPRING_JPA_DATABASE_PLATFORM}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: your-bucket-name